logo: /assets/img/logo.jpg

description:
description: |
  <p align="center">
  <a href="./Prasun_Kumar.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prasun-kumar-1708/">LinkedIn</a> |
  <a href="https://github.com/Prasun0512">GitHub</a> |
  <a href="https://www.youtube.com/@AIWizardry277">YouTube</a>  
  <br> ML & AI Engineer with 7+ years of experience, recently completed <b>PGDM in ML and AI</b> (<a href="https://www.credential.net/20453200-981b-4985-9ddf-2a44c5ee66cf#gs.cq8xsj">Credential</a>). With a strong background in Python, software development, and extensive machine learning concepts, I am confident in contributing significantly to any organization seeking to implement ML solutions. 
  
  <br>
theme: jekyll-theme-minimal 
github:
  is_project_page: false
