title: <p align="center"> Prasun Kumar </p>

logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="./Prasun_Kumar_Resume Ml.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prasun-kumar-1708/">LinkedIn</a> |
  <a href="https://github.com/Prasun0512">GitHub</a>
  
  <br> ML & AI Engineer with 1.5 year of experience in the domain and 5 years of experience in Python and Software Development, currently pursuing PGDM in ML and AI. With my strong background in Python and software development knowledge along with extensive machine learning concepts, I am confident that I
      can contribute significantly any organization seeking to implement ML solution. 
  
  <br>
theme: jekyll-theme-minimal 
github:
  is_project_page: false

