logo: /assets/img/logo.jpg

description:
description: |
  <p align="center">
  <a href="./Prasun_Kumar.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prasun-kumar-1708/">LinkedIn</a> |
  <a href="https://github.com/Prasun0512">GitHub</a> |
  <a href="https://www.youtube.com/@AIWizardry277">YouTube</a>  
  <br>  ML & AI Lead with over 7 years of experience. I have completed my <b>PGDM in ML and AI</b> (<a href="https://www.credential.net/20453200-981b-4985-9ddf-2a44c5ee66cf#gs.cq8xsj">Credential</a>). As a Deep Learning Expert, I have a deep proficiency in cutting-edge AI technologies and advanced machine learning techniques. I am highly skilled in Python, software development, and deep learning frameworks like TensorFlow, PyTorch, and Keras. I excel in developing and deploying scalable AI and ML solutions, with a focus on NLP and computer vision. My robust background also includes model deployment, monitoring, and maintenance in cloud environments such as AWS and Azure.
  
  <br> I've been recognized with multiple accolades, including the Technical Star Award and Superstar Award from Harbinger Group. My expertise in data preprocessing, feature engineering, hyperparameter tuning, and model optimization ensures top-notch model performance. With a strong ability to lead cross-functional teams and deliver high-impact AI and ML projects, I am confident in contributing significantly to any organization seeking innovative AI solutions.

  <br>
theme: jekyll-theme-minimal 
github:
  is_project_page: false
