<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prasun Kumar</title>
</head>
<body>
    <p align="center">
        <a href="./Prasun_Kumar.pdf">Resume</a> |
        <a href="https://www.linkedin.com/in/prasun-kumar-1708/">LinkedIn</a> |
        <a href="https://github.com/Prasun0512">GitHub</a> |
        <a href="https://www.youtube.com/@AIWizardry277">YouTube</a>
    </p>
    <p align="center">
        ML & AI Engineer with 7+ years of experience currently pursuing <b>PGDM in ML and AI</b>. With my strong background in Python and software development knowledge along with extensive machine learning concepts, I am confident that I can contribute significantly to any organization seeking to implement ML solutions.
    </p>
</body>
</html>
