logo: /assets/img/logo.jpg

description:
description: |
  <p align="center">
  <a href="./Prasun_Kumar.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/prasun-kumar-1708/">LinkedIn</a> |
  <a href="https://github.com/Prasun0512">GitHub</a> |
  <a href="https://www.youtube.com/@AIWizardry277">YouTube</a>
  
  <br> ML & AI Engineer with 7+ year of experience currently pursuing <b>PGDM in ML and AI</b>. With my strong background in Python and software development knowledge along with extensive machine learning concepts, I am confident that I
      can contribute significantly any organization seeking to implement ML solution. 
  <br> ML & AI Engineer with {{ site.time | date: "%Y" | minus: "2017" }}+ years of experience currently pursuing <b>PGDM in ML and AI</b>. With my strong background in Python and software development knowledge along with extensive machine learning concepts, I am confident that I can contribute significantly to any organization seeking to implement ML solutions. 
  
  <br>
theme: jekyll-theme-minimal 
github:
  is_project_page: false
