on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'      # or '3.3'
          bundler-cache: true      # installs & caches gems from Gemfile.lock

      # If your bootstrap does `bundle install`, keep it.
      - name: build
        run: script/bootstrap

      - name: test
        run: script/cibuild
